const keywordsForDamages = [
   "Danificado",
    "Falha",
    "Marcas",
    "Marcas de Uso",
    "Trincado",
    "Riscado",
    "Danos",
    "Manchas",
    "Marca de Agua",
    "Defeituoso",
    "Quebrado",
    "Quebrada",
    "Avariado",
    "Desgastado",
    "Desbotado",
    "Amassado",
    "Arranhado",
    "Encardido",
    "Enferrujado",
    "Rasgado",
    "Corroído",
    "Deformado",
    "Oxidado",
    "Deteriorado",
    "Fragilizado",
    "Descolado",
    "Manchado",
    "Queimado",
    "Desintegrado",
    "Estilhaçado",
    "Desalinhado",
    "Rachado",
    "Desbotamento",
    "Desgaste",
    "Fragilidade",
    "Enrugado",
    "Desmontado",
    "Folga",
    "Solto",
    "Deslocado",
    "Estragado",
    "Fendido",
    "Não Vincula",
    "Falha Opercional",
    "Falha Estrutural",
    "Dano Estético",
    "Não Funciona",
    "Não apresenta Funcionamento",
    "Não Liga",
];
const keywordsNoDamages = [
    "Sem Falha",
    "Leves Marcas de Uso",
    "Pequenos Arranhões",
    "Sinais Normais de Uso",
    "Levemente Desgastado",
    "Pequenas Imperfeições",
    "Nenhum Dano Significativo",
    "Sem Danos Graves",
    "Sem Danos Visíveis",
    "Leve Desbotamento",
    "Funcionalidade Completa",
    "Conservado",
    "Sem Rachaduras",
    "Operacional",
    "Sem Trincas",
    "Não Apresenta Danos",
    "Não Apresenta Falhas",
];

const othersKeyword = [
    // Direction
    "Direito",
    "Esquerdo",
    "Traseiro",
    "Frontal",
    "Dianteiro",
    "Central",
    "Superior",
    "Inferior",
    "Lateral",
    "Diagonal",
    "Baixo",
    "Meio",
    "Cima",
    "Pitch",
    "Yaw",
    "Roll",
    "Tilt",
    "Pan",
    "Externo",
    "Principal",
    // Itens
    "CoreBoard",
    "ESC",
    "IMU",
    "GPS",
    "Bussola",
    "RTK",
    "Bateria",
    "Motor",
    "Braço",
    "Eixo",
    "Tampa",
    "Cobertura",
    "Concha",
    "Caixa",
    "Compartimento",
    "Armação",
    "Lente",
    "Sensor",
    "Gimbal",
    "Motor",
    "Trem de Pouso",
    "Botão",
    "Conector",
    "Hélices",
    "Carregador",
]
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

const allKeyWords = [...keywordsForDamages,...keywordsNoDamages,...othersKeyword]